export const styles={
  'default':{
    backgroundColor:'black',
    color:'white'
  },
  "html":{
    backgroundColor:'#e44b23',
    color:'white'
  },
  "css":{
    backgroundColor:'#563d7c',
    color:'white'
  },
  "js":{
    backgroundColor:'#f1e05a',
    color:'black'
  },
  "ruby":{
    backgroundColor:'#701516',
    color:'white'
  },
  "java":{
    backgroundColor:'#b07219',
    color:'white'
  },
  "c++":{
    backgroundColor:'#f34b7d',
    color:'white'
  },
  "react":{
    backgroundColor:'#20232a',
    color:'#61DBFB'
  },
  "nodejs":{
    backgroundColor:'#68A063',
    color:'#FFF'
  },
  "express":{
    backgroundColor:'#259dff',
    color:'white'
  },
  "mongodb":{
    backgroundColor:'#4DB33D',
    color:'#FFF'
  },
  "___":{
    backgroundColor:'#000000',
    color:'white'
  },
 
}
